name: generate-resume-pdf

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate PDF with Puppeteer
        run: |
          mkdir -p assets
          npx puppeteer@latest print --format=A4 --margin-top=0.5in --margin-bottom=0.5in --margin-left=0.5in --margin-right=0.5in "https://joedunn123456789.github.io/Bootstrap5-Resume/" assets/resume.pdf

      - name: Commit PDF back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add assets/resume.pdf
          git commit -m "Auto-update resume.pdf" || echo "No changes to commit"
          git push